# Generated by Django 5.0.4 on 2024-04-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("serving_size_g", models.FloatField()),
                ("calories", models.FloatField()),
                ("protein_g", models.FloatField()),
                ("suger_g", models.FloatField()),
                ("fat_total_g", models.FloatField()),
                ("carbohydrates_total_g", models.FloatField(blank=True, null=True)),
                ("cholesterol_mg", models.FloatField()),
                ("potassium_mg", models.FloatField(blank=True, null=True)),
                ("sodium_mg", models.FloatField(blank=True, null=True)),
                ("fiber_g", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ("title",),
            },
        ),
    ]
