# Generated by Django 5.0.4 on 2024-04-05 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={"ordering": ("name",)},
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="suger_g",
            new_name="sugar_g",
        ),
    ]
