# Generated by Django 5.0.4 on 2024-04-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nutrition", "0002_alter_ingredient_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="calories",
            field=models.FloatField(help_text="Calories per serving."),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="carbohydrates_total_g",
            field=models.FloatField(
                blank=True,
                help_text="Total carbohydrates per serving in grams.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="cholesterol_mg",
            field=models.FloatField(
                help_text="Cholesterol content per serving in milligrams."
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="fat_total_g",
            field=models.FloatField(
                help_text="Total fat content per serving in grams."
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="fiber_g",
            field=models.FloatField(
                blank=True, help_text="Fiber content per serving in grams.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(help_text="Name of the ingredient.", max_length=256),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="potassium_mg",
            field=models.FloatField(
                blank=True,
                help_text="Potassium content per serving in milligrams.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="protein_g",
            field=models.FloatField(help_text="Protein content per serving in grams."),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="serving_size_g",
            field=models.FloatField(help_text="Serving size in grams."),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="sodium_mg",
            field=models.FloatField(
                blank=True,
                help_text="Sodium content per serving in milligrams.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="sugar_g",
            field=models.FloatField(help_text="Sugar content per serving in grams."),
        ),
    ]
