# Generated by Django 5.0.4 on 2024-04-05 12:08

import django.db.models.deletion
import recipes_manager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("nutrition", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="IngredientRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Ingredient", max_length=256)),
                ("quantity", models.FloatField()),
                (
                    "measuring_unit",
                    models.CharField(
                        choices=[
                            ("mg", "Milligram"),
                            ("g", "Gram"),
                            ("kg", "Kg"),
                            ("ml", "Milliliter"),
                            ("l", "Liter"),
                        ],
                        default="g",
                        max_length=256,
                    ),
                ),
                (
                    "ingredient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nutrition.ingredient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cooking_time", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=256)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=recipes_manager.models.user_directory_path,
                    ),
                ),
                ("description", models.TextField()),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes_manager.category",
                    ),
                ),
                (
                    "custom_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingredients",
                    models.ManyToManyField(
                        through="recipes_manager.IngredientRecipe",
                        to="nutrition.ingredient",
                    ),
                ),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.AddField(
            model_name="ingredientrecipe",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recipes_manager.recipe"
            ),
        ),
    ]
