# Generated by Django 5.0.4 on 2024-04-11 10:20

import recipes_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes_manager", "0002_instruction"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=recipes_manager.models.user_directory_path,
            ),
        ),
    ]
