# Generated by Django 5.0.4 on 2024-04-22 12:35

import django.db.models.deletion
import recipes_manager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nutrition", "0003_alter_ingredient_calories_and_more"),
        ("recipes_manager", "0003_recipe_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(help_text="Title of the category.", max_length=256),
        ),
        migrations.AlterField(
            model_name="ingredientrecipe",
            name="ingredient",
            field=models.OneToOneField(
                help_text="The ingredient used in this recipe.",
                on_delete=django.db.models.deletion.CASCADE,
                to="nutrition.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientrecipe",
            name="measuring_unit",
            field=models.CharField(
                choices=[
                    ("mg", "Milligram"),
                    ("g", "Gram"),
                    ("kg", "Kilogram"),
                    ("ml", "Milliliter"),
                    ("l", "Liter"),
                ],
                default="g",
                help_text="Unit of measurement for the quantity.",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="ingredientrecipe",
            name="quantity",
            field=models.FloatField(
                help_text="Quantity of the ingredient needed for the recipe."
            ),
        ),
        migrations.AlterField(
            model_name="ingredientrecipe",
            name="recipe",
            field=models.ForeignKey(
                help_text="The recipe to which this ingredient belongs.",
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes_manager.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientrecipe",
            name="title",
            field=models.CharField(
                default="Ingredient",
                help_text="Title of the ingredient in this recipe (optional).",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="description",
            field=models.TextField(
                help_text="The detailed description of this instruction."
            ),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="An optional file containing additional information for this instruction.",
                null=True,
                upload_to=recipes_manager.models.user_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="number",
            field=models.IntegerField(
                help_text="The order or sequence number of this instruction within the recipe."
            ),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="recipe",
            field=models.ForeignKey(
                help_text="The recipe to which this instruction belongs.",
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes_manager.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.ForeignKey(
                help_text="The category to which this recipe belongs.",
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes_manager.category",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.IntegerField(
                default=0,
                help_text="The time it takes to cook this recipe (in minutes).",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="custom_user",
            field=models.ForeignKey(
                help_text="The user who created this recipe.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(help_text="A description of the recipe."),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="A file containing the recipe instructions (optional).",
                null=True,
                upload_to=recipes_manager.models.user_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An image representing the recipe (optional).",
                null=True,
                upload_to=recipes_manager.models.user_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                help_text="The ingredients required for this recipe.",
                through="recipes_manager.IngredientRecipe",
                to="nutrition.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="published_date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time when this recipe was published.",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(
                help_text="The title of the recipe.", max_length=256
            ),
        ),
    ]
