# Generated by Django 5.0.4 on 2024-04-05 11:48

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=users.models.user_directory_path
            ),
        ),
    ]
